// Code generated by rclgo-gen. DO NOT EDIT.

package px4_msgs_srv

/*
#cgo LDFLAGS: "-L/home/dave/Git/merlin/owl_ws/install/px4_msgs/lib" "-Wl,-rpath=/home/dave/Git/merlin/owl_ws/install/px4_msgs/lib"
#cgo LDFLAGS: "-L/home/dave/Git/merlin/owl_ws/install/owl_model/lib" "-Wl,-rpath=/home/dave/Git/merlin/owl_ws/install/owl_model/lib"
#cgo LDFLAGS: "-L/opt/ros/humble/lib" "-Wl,-rpath=/opt/ros/humble/lib"

#cgo LDFLAGS: -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lpx4_msgs__rosidl_typesupport_c -lpx4_msgs__rosidl_generator_c
#cgo LDFLAGS: -lpx4_msgs__rosidl_typesupport_c -lpx4_msgs__rosidl_generator_c

#cgo CFLAGS: "-I/home/dave/Git/merlin/owl_ws/install/px4_msgs/include/action_msgs"
#cgo CFLAGS: "-I/home/dave/Git/merlin/owl_ws/install/px4_msgs/include/builtin_interfaces"
#cgo CFLAGS: "-I/home/dave/Git/merlin/owl_ws/install/px4_msgs/include/example_interfaces"
#cgo CFLAGS: "-I/home/dave/Git/merlin/owl_ws/install/px4_msgs/include/geometry_msgs"
#cgo CFLAGS: "-I/home/dave/Git/merlin/owl_ws/install/px4_msgs/include/rcutils"
#cgo CFLAGS: "-I/home/dave/Git/merlin/owl_ws/install/px4_msgs/include/rosidl_dynamic_typesupport"
#cgo CFLAGS: "-I/home/dave/Git/merlin/owl_ws/install/px4_msgs/include/rosidl_runtime_c"
#cgo CFLAGS: "-I/home/dave/Git/merlin/owl_ws/install/px4_msgs/include/rosidl_typesupport_interface"
#cgo CFLAGS: "-I/home/dave/Git/merlin/owl_ws/install/px4_msgs/include/sensor_msgs"
#cgo CFLAGS: "-I/home/dave/Git/merlin/owl_ws/install/px4_msgs/include/service_msgs"
#cgo CFLAGS: "-I/home/dave/Git/merlin/owl_ws/install/px4_msgs/include/std_msgs"
#cgo CFLAGS: "-I/home/dave/Git/merlin/owl_ws/install/px4_msgs/include/std_srvs"
#cgo CFLAGS: "-I/home/dave/Git/merlin/owl_ws/install/px4_msgs/include/test_msgs"
#cgo CFLAGS: "-I/home/dave/Git/merlin/owl_ws/install/px4_msgs/include/type_description_interfaces"
#cgo CFLAGS: "-I/home/dave/Git/merlin/owl_ws/install/px4_msgs/include/unique_identifier_msgs"
#cgo CFLAGS: "-I/home/dave/Git/merlin/owl_ws/install/px4_msgs/include/px4_msgs"

#cgo CFLAGS: "-I/home/dave/Git/merlin/owl_ws/install/px4_msgs/include/px4_msgs"

#cgo CFLAGS: "-I/home/dave/Git/merlin/owl_ws/install/owl_model/include/action_msgs"
#cgo CFLAGS: "-I/home/dave/Git/merlin/owl_ws/install/owl_model/include/builtin_interfaces"
#cgo CFLAGS: "-I/home/dave/Git/merlin/owl_ws/install/owl_model/include/example_interfaces"
#cgo CFLAGS: "-I/home/dave/Git/merlin/owl_ws/install/owl_model/include/geometry_msgs"
#cgo CFLAGS: "-I/home/dave/Git/merlin/owl_ws/install/owl_model/include/rcutils"
#cgo CFLAGS: "-I/home/dave/Git/merlin/owl_ws/install/owl_model/include/rosidl_dynamic_typesupport"
#cgo CFLAGS: "-I/home/dave/Git/merlin/owl_ws/install/owl_model/include/rosidl_runtime_c"
#cgo CFLAGS: "-I/home/dave/Git/merlin/owl_ws/install/owl_model/include/rosidl_typesupport_interface"
#cgo CFLAGS: "-I/home/dave/Git/merlin/owl_ws/install/owl_model/include/sensor_msgs"
#cgo CFLAGS: "-I/home/dave/Git/merlin/owl_ws/install/owl_model/include/service_msgs"
#cgo CFLAGS: "-I/home/dave/Git/merlin/owl_ws/install/owl_model/include/std_msgs"
#cgo CFLAGS: "-I/home/dave/Git/merlin/owl_ws/install/owl_model/include/std_srvs"
#cgo CFLAGS: "-I/home/dave/Git/merlin/owl_ws/install/owl_model/include/test_msgs"
#cgo CFLAGS: "-I/home/dave/Git/merlin/owl_ws/install/owl_model/include/type_description_interfaces"
#cgo CFLAGS: "-I/home/dave/Git/merlin/owl_ws/install/owl_model/include/unique_identifier_msgs"
#cgo CFLAGS: "-I/home/dave/Git/merlin/owl_ws/install/owl_model/include/px4_msgs"

#cgo CFLAGS: "-I/home/dave/Git/merlin/owl_ws/install/owl_model/include/px4_msgs"

#cgo CFLAGS: "-I/opt/ros/humble/include/action_msgs"
#cgo CFLAGS: "-I/opt/ros/humble/include/builtin_interfaces"
#cgo CFLAGS: "-I/opt/ros/humble/include/example_interfaces"
#cgo CFLAGS: "-I/opt/ros/humble/include/geometry_msgs"
#cgo CFLAGS: "-I/opt/ros/humble/include/rcutils"
#cgo CFLAGS: "-I/opt/ros/humble/include/rosidl_dynamic_typesupport"
#cgo CFLAGS: "-I/opt/ros/humble/include/rosidl_runtime_c"
#cgo CFLAGS: "-I/opt/ros/humble/include/rosidl_typesupport_interface"
#cgo CFLAGS: "-I/opt/ros/humble/include/sensor_msgs"
#cgo CFLAGS: "-I/opt/ros/humble/include/service_msgs"
#cgo CFLAGS: "-I/opt/ros/humble/include/std_msgs"
#cgo CFLAGS: "-I/opt/ros/humble/include/std_srvs"
#cgo CFLAGS: "-I/opt/ros/humble/include/test_msgs"
#cgo CFLAGS: "-I/opt/ros/humble/include/type_description_interfaces"
#cgo CFLAGS: "-I/opt/ros/humble/include/unique_identifier_msgs"
#cgo CFLAGS: "-I/opt/ros/humble/include/px4_msgs"

#cgo CFLAGS: "-I/opt/ros/humble/include/px4_msgs"
*/
import "C"
