// Code generated by rclgo-gen. DO NOT EDIT.

package px4_msgs_msg

import (
	"unsafe"

	"github.com/merlindrones/rclgo/pkg/rclgo"
	primitives "github.com/merlindrones/rclgo/pkg/rclgo/primitives"
	"github.com/merlindrones/rclgo/pkg/rclgo/typemap"
	"github.com/merlindrones/rclgo/pkg/rclgo/types"
)

/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <px4_msgs/msg/mavlink_log.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("px4_msgs/MavlinkLog", MavlinkLogTypeSupport)
	typemap.RegisterMessage("px4_msgs/msg/MavlinkLog", MavlinkLogTypeSupport)
}

const (
	MavlinkLog_ORB_QUEUE_LENGTH uint8 = 8
)

type MavlinkLog struct {
	Timestamp uint64    `yaml:"timestamp"` // time since system start (microseconds)
	Text      [127]byte `yaml:"text"`
	Severity  uint8     `yaml:"severity"` // log level (same as in the linux kernel, starting with 0)
}

// NewMavlinkLog creates a new MavlinkLog with default values.
func NewMavlinkLog() *MavlinkLog {
	self := MavlinkLog{}
	self.SetDefaults()
	return &self
}

func (t *MavlinkLog) Clone() *MavlinkLog {
	c := &MavlinkLog{}
	c.Timestamp = t.Timestamp
	c.Text = t.Text
	c.Severity = t.Severity
	return c
}

func (t *MavlinkLog) CloneMsg() types.Message {
	return t.Clone()
}

func (t *MavlinkLog) SetDefaults() {
	t.Timestamp = 0
	t.Text = [127]byte{}
	t.Severity = 0
}

func (t *MavlinkLog) GetTypeSupport() types.MessageTypeSupport {
	return MavlinkLogTypeSupport
}

// MavlinkLogPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type MavlinkLogPublisher struct {
	*rclgo.Publisher
}

// NewMavlinkLogPublisher creates and returns a new publisher for the
// MavlinkLog
func NewMavlinkLogPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*MavlinkLogPublisher, error) {
	pub, err := node.NewPublisher(topic_name, MavlinkLogTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &MavlinkLogPublisher{pub}, nil
}

func (p *MavlinkLogPublisher) Publish(msg *MavlinkLog) error {
	return p.Publisher.Publish(msg)
}

// MavlinkLogSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type MavlinkLogSubscription struct {
	*rclgo.Subscription
}

// MavlinkLogSubscriptionCallback type is used to provide a subscription
// handler function for a MavlinkLogSubscription.
type MavlinkLogSubscriptionCallback func(msg *MavlinkLog, info *rclgo.MessageInfo, err error)

// NewMavlinkLogSubscription creates and returns a new subscription for the
// MavlinkLog
func NewMavlinkLogSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback MavlinkLogSubscriptionCallback) (*MavlinkLogSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg MavlinkLog
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, MavlinkLogTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &MavlinkLogSubscription{sub}, nil
}

func (s *MavlinkLogSubscription) TakeMessage(out *MavlinkLog) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneMavlinkLogSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneMavlinkLogSlice(dst, src []MavlinkLog) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var MavlinkLogTypeSupport types.MessageTypeSupport = _MavlinkLogTypeSupport{}

type _MavlinkLogTypeSupport struct{}

func (t _MavlinkLogTypeSupport) New() types.Message {
	return NewMavlinkLog()
}

func (t _MavlinkLogTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.px4_msgs__msg__MavlinkLog
	return (unsafe.Pointer)(C.px4_msgs__msg__MavlinkLog__create())
}

func (t _MavlinkLogTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.px4_msgs__msg__MavlinkLog__destroy((*C.px4_msgs__msg__MavlinkLog)(pointer_to_free))
}

func (t _MavlinkLogTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*MavlinkLog)
	mem := (*C.px4_msgs__msg__MavlinkLog)(dst)
	mem.timestamp = C.uint64_t(m.Timestamp)
	cSlice_text := mem.text[:]
	primitives.Char__Array_to_C(*(*[]primitives.CChar)(unsafe.Pointer(&cSlice_text)), m.Text[:])
	mem.severity = C.uint8_t(m.Severity)
}

func (t _MavlinkLogTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*MavlinkLog)
	mem := (*C.px4_msgs__msg__MavlinkLog)(ros2_message_buffer)
	m.Timestamp = uint64(mem.timestamp)
	cSlice_text := mem.text[:]
	primitives.Char__Array_to_Go(m.Text[:], *(*[]primitives.CChar)(unsafe.Pointer(&cSlice_text)))
	m.Severity = uint8(mem.severity)
}

func (t _MavlinkLogTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__px4_msgs__msg__MavlinkLog())
}

type CMavlinkLog = C.px4_msgs__msg__MavlinkLog
type CMavlinkLog__Sequence = C.px4_msgs__msg__MavlinkLog__Sequence

func MavlinkLog__Sequence_to_Go(goSlice *[]MavlinkLog, cSlice CMavlinkLog__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]MavlinkLog, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		MavlinkLogTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func MavlinkLog__Sequence_to_C(cSlice *CMavlinkLog__Sequence, goSlice []MavlinkLog) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.px4_msgs__msg__MavlinkLog)(C.malloc(C.sizeof_struct_px4_msgs__msg__MavlinkLog * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		MavlinkLogTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func MavlinkLog__Array_to_Go(goSlice []MavlinkLog, cSlice []CMavlinkLog) {
	for i := 0; i < len(cSlice); i++ {
		MavlinkLogTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func MavlinkLog__Array_to_C(cSlice []CMavlinkLog, goSlice []MavlinkLog) {
	for i := 0; i < len(goSlice); i++ {
		MavlinkLogTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
